name: build-images

on:
  push:
    branches:
      - main

env:
  LOCATION: EastUS
  DESTINATION_RESOURCE_GROUP_NAME: dsr-images-rg
  DESTINATION_IMAGE_GALLERY_NAME: dsrimagegallery

jobs:
  prepare-image-gallery:
    runs-on: ubuntu-latest
    name: Prepare Image Gallery

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image Gallery Template
        uses: azure/CLI@v1
        with:
          azcliversion: 2.24.2
          inlineScript: |
            az deployment sub create \
              --location $LOCATION \
              --template-file bicep/main.bicep \
              --parameters location=$LOCATION resourceGroupName=$DESTINATION_RESOURCE_GROUP_NAME imageGalleryName=$DESTINATION_IMAGE_GALLERY_NAME

  build-MicrosoftWindowsServer2016DatacenterVsCode:
    runs-on: ubuntu-latest
    needs: prepare-image-gallery
    name: Build MicrosoftWindowsServer2016DatacenterVsCode
    env:
      PACKER_FILE: "packer/microsoft-windows-server.pkr.hcl"
      IMAGE_NAME: MicrosoftWindowsServer2016DatacenterVsCode
      IMAGE_VERSION: 1.0.0
      AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      AZURE_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
      AZURE_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      AZURE_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only"
          target: ${{ env.PACKER_FILE }}

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var azure_subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }} -var azure_tenant_id=${{ env.AZURE_TENANT_ID }} -var azure_client_id=${{ env.AZURE_CLIENT_ID }} -var azure_client_secret=${{ env.AZURE_CLIENT_SECRET }} -var location=${{ env.LOCATION }} -var destination_resource_group_name=${{ env.DESTINATION_RESOURCE_GROUP_NAME }} -var destination_image_gallery_name=${{ env.DESTINATION_IMAGE_GALLERY_NAME }} -var image_name=${{ env.IMAGE_NAME }} -var image_version=${{ env.IMAGE_VERSION }} "
          target: ${{ env.PACKER_FILE }}
        env:
          PACKER_LOG: 1